color0 #f9f9fc
color1 #ba1a1a
color2 #006591
color3 #4f606e
color4 #64597c
color5 #89ceff
color6 #b7c9d9
color7 #191c1e
color8 #71787e
color9 #ba1a1a
color10 #006591
color11 #4f606e
color12 #64597c
color13 #89ceff
color14 #b7c9d9
color15 #191c1e

cursor                #191c1e
cursor_text_color     #f9f9fc
background            #f9f9fc
foreground            #191c1e
selection_foreground  #41474d
selection_background  #dde3ea
active_border_color   #006591
inactive_border_color #dde3ea
url_color             #006591

active_tab_foreground   #ffffff
active_tab_background   #006591
inactive_tab_foreground #41474d
inactive_tab_background #dde3ea
cursor_trail_color      #41474d
